## Extract - Leitura dos dados

In [97]:
import pandas as pd
import os 
import chardet
from dotenv import load_dotenv
from dotenv import load_dotenv

# Carrega as variáveis do arquivo .env
# Como você está dentro da pasta "notebooks", usamos "../.env" para subir um nível
load_dotenv("../.env")
# Pega variável de ambiente
RAW_DATA_PATH = os.getenv("RAW_DATA_PATH")

In [98]:
# Abre o arquivo no modo binário ("rb" = read binary)
# Isso é necessário porque a detecção de encoding precisa analisar os bytes brutos,
# e não o texto já decodificado.
with open(RAW_DATA_PATH, "rb") as f:
    
    # Lê TODO o conteúdo do arquivo como uma sequência de bytes
    # e utiliza a biblioteca chardet para detectar automaticamente o encoding
    resultado = chardet.detect(f.read())
print(resultado)
# Salvando variável 
encoding = resultado["encoding"]

{'encoding': 'ascii', 'confidence': 1.0, 'language': 'en', 'mime_type': 'text/plain'}

In [99]:
#Leitura arquivo
df = pd.read_csv(RAW_DATA_PATH, encoding="latin-1", sep=",")

## Análise Exploratória de Dados (EDA)

In [92]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  str
 1   StockCode    541909 non-null  str
 2   Description  540455 non-null  str
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  str
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  str
dtypes: float64(2), int64(1), str(5)
memory usage: 33.1 MB

In [95]:
df.shape

(534129, 8)

In [104]:
teste_description = df.groupby('StockCode')['Description'].nunique()
teste_description = teste_description[teste_description > 1]
teste_description

StockCode
10080           2
10133           2
15058A          2
15058C          2
16008           2
               ..
90195A          2
90210D          2
DCGS0003        2
DCGS0069        2
gift_0001_20    2
Name: Description, Length: 650, dtype: int64

In [107]:
print(df['CustomerID'].isnull().sum())
print(df['CustomerID'].isnull().mean())

135035
0.2516309847029381

In [ ]:
print(df.isna().sum())

df_teste = df[df['CustomerID'].isna()]
df_teste


#Removendo valores negativos
df = df[df['UnitPrice'] > 0].drop_duplicates().reset_index(drop=True)
df

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
536634,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France
536635,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France
536636,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France
536637,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France
536638,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France

In [35]:
df.shape #Quantidade de linhas e colunas

(541909, 8)

In [56]:
df.isna().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135037
Country             0
dtype: int64

In [54]:
#Analisando os resultados duplicados
df_filtro = df[df.duplicated(keep=False)].sort_values(by='Description', ascending=False)
df_filtro

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
104355,545166,84832,ZINC WILLIE WINKIE CANDLE STICK,1,2/28/2011 14:03,0.85,17027.0,United Kingdom
104362,545166,84832,ZINC WILLIE WINKIE CANDLE STICK,1,2/28/2011 14:03,0.85,17027.0,United Kingdom
468873,576559,23151,ZINC SWEETHEART SOAP DISH,1,11/15/2011 13:19,2.49,14711.0,United Kingdom
468850,576559,23151,ZINC SWEETHEART SOAP DISH,1,11/15/2011 13:19,2.49,14711.0,United Kingdom
144648,548792,84836,ZINC METAL HEART DECORATION,1,4/4/2011 12:42,1.25,14711.0,United Kingdom
...,...,...,...,...,...,...,...,...
460098,575895,23345,DOLLY GIRL BEAKER,1,11/11/2011 14:50,1.25,17052.0,United Kingdom
483390,577503,72800B,4 PURPLE FLOCK DINNER CANDLES,1,11/20/2011 12:34,2.55,18110.0,United Kingdom
160509,550459,72800B,4 PURPLE FLOCK DINNER CANDLES,1,4/18/2011 13:17,2.55,18116.0,United Kingdom
160498,550459,72800B,4 PURPLE FLOCK DINNER CANDLES,1,4/18/2011 13:17,2.55,18116.0,United Kingdom
483414,577503,72800B,4 PURPLE FLOCK DINNER CANDLES,1,11/20/2011 12:34,2.55,18110.0,United Kingdom

In [57]:
df.describe()

            Quantity      UnitPrice     CustomerID
count  536641.000000  536641.000000  401604.000000
mean        9.620029       4.632656   15281.160818
std       219.130156      97.233118    1714.006089
min    -80995.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13939.000000
50%         3.000000       2.080000   15145.000000
75%        10.000000       4.130000   16784.000000
max     80995.000000   38970.000000   18287.000000

In [34]:
df.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='str')

# Tratativas

Data Quality & Anomalias

In [59]:
df = df.drop_duplicates().reset_index(drop=True)
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
536636,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France
536637,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France
536638,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France
536639,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France
536640,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France

In [13]:
### Renomeando Columns
colunas_traduzidas = {
    "InvoiceNo": "numero_fatura",
    "StockCode": "codigo_produto",
    "Description": "descricao",
    "Quantity": "quantidade",
    "InvoiceDate": "data_fatura",
    "UnitPrice": "preco_unitario",
    "CustomerID": "id_cliente",
    "Country": "pais"
}


df = df.rename(columns=colunas_traduzidas)
df.columns

Index(['numero_fatura', 'codigo_produto', 'descricao', 'quantidade',
       'data_fatura', 'preco_unitario', 'id_cliente', 'pais'],
      dtype='str')

In [14]:
### Tratamento coluna País/Country

#Unifica os valores para visualização
print(df['pais'].unique()) 

# Tratamento: Retira os espaços vázios, deixa a formatação Title e substitui os valores srt
df['pais'] = (df['pais'].str.strip().str.title().replace({
        "Eire": "Ireland",
        "Usa": "United States",
        "Rsa": "South Africa",
        "Unspecified": None,
        "European Community": "Europe"
    })) 


print(df['pais'].isnull().sum())

df = df.dropna(subset=['pais'])

df['pais'] = df['pais'].astype('category')

<StringArray>
[      'United Kingdom',               'France',            'Australia',
          'Netherlands',              'Germany',               'Norway',
                 'EIRE',          'Switzerland',                'Spain',
               'Poland',             'Portugal',                'Italy',
              'Belgium',            'Lithuania',                'Japan',
              'Iceland',      'Channel Islands',              'Denmark',
               'Cyprus',               'Sweden',              'Austria',
               'Israel',              'Finland',              'Bahrain',
               'Greece',            'Hong Kong',            'Singapore',
              'Lebanon', 'United Arab Emirates',         'Saudi Arabia',
       'Czech Republic',               'Canada',          'Unspecified',
               'Brazil',                  'USA',   'European Community',
                'Malta',                  'RSA']
Length: 38, dtype: str
446

In [ ]:
### Tratamento coluna data_fatura

# Converte a coluna 'data_fatura' para o tipo datetime
# errors="coerce" garante que valores inválidos sejam transformados em NaT (Not a Time),
# evitando que o código quebre durante a execução
df['data_fatura'] = pd.to_datetime(df['data_fatura'], errors="coerce")

In [16]:
### Tratamento coluna descricao

# Cria um "mapa" (tipo dicionário) de código_produto -> descricao
# Etapas:
# 1. Remove linhas onde a descrição é nula (não servem para referência)
# 2. Remove duplicados de codigo_produto (mantém apenas uma descrição por produto)
# 3. Define codigo_produto como índice
# 4. Seleciona apenas a coluna 'descricao', virando uma Series (tipo um dicionário)

mapa_produtos = (
    df
    .dropna(subset=["descricao"])                 # Remove descrições nulas
    .drop_duplicates("codigo_produto")            # Garante 1 descrição por produto
    .set_index("codigo_produto")["descricao"]     # Cria mapeamento: codigo -> descricao
)


# Preenche valores nulos da coluna 'descricao'
# Para cada linha:
# - pega o codigo_produto
# - busca no mapa_produtos a descrição correspondente
# - preenche apenas onde 'descricao' está NaN

df["descricao"] = df["descricao"].fillna(
    df["codigo_produto"].map(mapa_produtos)
)

In [17]:
df.isna().sum()

numero_fatura          0
codigo_produto         0
descricao            112
quantidade             0
data_fatura            0
preco_unitario         0
id_cliente        134878
pais                   0
dtype: int64

In [18]:
df['descricao'].isna().sum()

np.int64(112)

In [19]:
df_nan = df[df['descricao'].isna()]
df_nan.nunique()

df_nan.sample(10)

,numero_fatura,codigo_produto,descricao,quantidade,data_fatura,preco_unitario,id_cliente,pais
279252,561250,DCGS0071,NaN,-2,2011-07-26 11:51:00,0.0,NaN,United Kingdom
279257,561255,DCGS0066P,NaN,-3,2011-07-26 11:52:00,0.0,NaN,United Kingdom
75242,542566,84964B,NaN,-1,2011-01-28 14:53:00,0.0,NaN,United Kingdom
201756,554320,16053,NaN,-102,2011-05-23 15:32:00,0.0,NaN,United Kingdom
75237,542561,84424A,NaN,-1,2011-01-28 14:52:00,0.0,NaN,United Kingdom
143303,548677,72781,NaN,-30,2011-04-01 16:40:00,0.0,NaN,United Kingdom
145260,548890,84876C,NaN,-19,2011-04-04 15:26:00,0.0,NaN,United Kingdom
171728,551454,78027,NaN,-3,2011-04-28 16:02:00,0.0,NaN,United Kingdom
172870,551571,47591A,NaN,-6,2011-05-03 11:14:00,0.0,NaN,United Kingdom
150150,549332,84864A,NaN,-2,2011-04-08 10:55:00,0.0,NaN,United Kingdom

## TESTE

In [20]:
df_filtro = df[
    df["pais"].isna() |
    df["descricao"].isna() |
    df["id_cliente"].isna()
]

df_filtro.info()

<class 'pandas.DataFrame'>
Index: 134878 entries, 622 to 541540
Data columns (total 8 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   numero_fatura   134878 non-null  str
 1   codigo_produto  134878 non-null  str
 2   descricao       134766 non-null  str
 3   quantidade      134878 non-null  int64
 4   data_fatura     134878 non-null  datetime64[us]
 5   preco_unitario  134878 non-null  float64
 6   id_cliente      0 non-null       float64
 7   pais            134878 non-null  category
dtypes: category(1), datetime64[us](1), float64(2), int64(1), str(3)
memory usage: 8.4 MB

In [21]:
df_filtro.reset_index(drop=True)

df_filtro_preco = df[df['preco_unitario'] == 0]
df_filtro_preco

,numero_fatura,codigo_produto,descricao,quantidade,data_fatura,preco_unitario,id_cliente,pais
622,536414,22139,RETROSPOT TEA SET CERAMIC 11 PC,56,2010-12-01 11:52:00,0.0,NaN,United Kingdom
1970,536545,21134,NaN,1,2010-12-01 14:32:00,0.0,NaN,United Kingdom
1971,536546,22145,CHRISTMAS CRAFT HEART STOCKING,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1972,536547,37509,NEW ENGLAND MUG W GIFT BOX,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1987,536549,85226A,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
...,...,...,...,...,...,...,...,...
536981,581234,72817,SET OF 2 CHRISTMAS DECOUPAGE CANDLE,27,2011-12-08 10:33:00,0.0,NaN,United Kingdom
538504,581406,46000M,POLYESTER FILLER PAD 45x45cm,240,2011-12-08 13:58:00,0.0,NaN,United Kingdom
538505,581406,46000S,POLYESTER FILLER PAD 40x40cm,300,2011-12-08 13:58:00,0.0,NaN,United Kingdom
538554,581408,85175,CACTI T-LIGHT CANDLES,20,2011-12-08 14:06:00,0.0,NaN,United Kingdom
538919,581422,23169,smashed,-235,2011-12-08 15:24:00,0.0,NaN,United Kingdom

In [22]:
df = df.dropna(
    subset=["pais", "descricao", "id_cliente"],
    how="any"  # padrão, mas bom deixar explícito
)

# Outros

In [23]:

'''
df.isnull().sum() #FAZER TRATAMENTO DOS NULLS

df = df.drop_duplicates(subset=["CustomerID"])

print(f"Quantidade de linhas: {df.shape[0]}\nQuantidade de Colunas: {df.shape[1]} ") 

df = df.drop_duplicates().reset_index(drop=True)
df 
'''

'\ndf.isnull().sum() #FAZER TRATAMENTO DOS NULLS\n\ndf = df.drop_duplicates(subset=["CustomerID"])\n\nprint(f"Quantidade de linhas: {df.shape[0]}\nQuantidade de Colunas: {df.shape[1]} ") \n\ndf = df.drop_duplicates().reset_index(drop=True)\ndf \n'

In [24]:
df.shape

#df.info()

(406585, 8)