## Leitura dos dados

In [115]:
import pandas as pd
import os 
import chardet
from dotenv import load_dotenv
from dotenv import load_dotenv

# Carrega as variáveis do arquivo .env
# Como você está dentro da pasta "notebooks", usamos "../.env" para subir um nível
load_dotenv("../.env")
# Pega variável de ambiente
RAW_DATA_PATH = os.getenv("RAW_DATA_PATH")

In [116]:
# Abre o arquivo no modo binário ("rb" = read binary)
# Isso é necessário porque a detecção de encoding precisa analisar os bytes brutos,
# e não o texto já decodificado.
with open(RAW_DATA_PATH, "rb") as f:
    
    # Lê TODO o conteúdo do arquivo como uma sequência de bytes
    # e utiliza a biblioteca chardet para detectar automaticamente o encoding
    resultado = chardet.detect(f.read())
print(resultado)
# Salvando variável 
encoding = resultado["encoding"]

{'encoding': 'ascii', 'confidence': 1.0, 'language': 'en', 'mime_type': 'text/plain'}

In [117]:
#Leitura arquivo
df = pd.read_csv(RAW_DATA_PATH, encoding="latin-1", sep=",")

## Análise Exploratória de Dados (EDA)

In [118]:
print(df.sample(5))

       InvoiceNo StockCode                      Description  Quantity  \
387784    570388     21212  PACK OF 72 RETROSPOT CAKE CASES        24
126407    547075     22980           PANTRY SCRUBBING BRUSH        12
267886    560366     23086       ZINC  STAR T-LIGHT HOLDER         16
484430    577531     23201               JUMBO BAG ALPHABET         5
358368    568143     23286         BLUE VINTAGE SPOT BEAKER         8

             InvoiceDate  UnitPrice  CustomerID         Country
387784  10/10/2011 12:37       0.55     14911.0            EIRE
126407   3/20/2011 14:35       1.65     15288.0  United Kingdom
267886   7/18/2011 12:19       1.25     16859.0  United Kingdom
484430  11/20/2011 13:58       4.13         NaN  United Kingdom
358368   9/25/2011 11:28       0.85     13266.0  United Kingdom

In [119]:
df.shape #Quantidade de linhas e colunas

(541909, 8)

In [126]:

df.duplicated().sum()

np.int64(5268)

In [127]:
df.describe()

          quantidade  preco_unitario     id_cliente
count  541909.000000   541909.000000  406829.000000
mean        9.552250        4.611114   15287.690570
std       218.081158       96.759853    1713.600303
min    -80995.000000   -11062.060000   12346.000000
25%         1.000000        1.250000   13953.000000
50%         3.000000        2.080000   15152.000000
75%        10.000000        4.130000   16791.000000
max     80995.000000    38970.000000   18287.000000

In [112]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   numero_fatura   541909 non-null  str
 1   codigo_produto  541909 non-null  str
 2   descricao       540455 non-null  str
 3   quantidade      541909 non-null  int64
 4   data_fatura     541909 non-null  str
 5   preco_unitario  541909 non-null  float64
 6   id_cliente      406829 non-null  float64
 7   pais            541909 non-null  str
dtypes: float64(2), int64(1), str(5)
memory usage: 33.1 MB

In [130]:
df.columns

Index(['numero_fatura', 'codigo_produto', 'descricao', 'quantidade',
       'data_fatura', 'preco_unitario', 'id_cliente', 'pais'],
      dtype='str')

## Tratativas

### Tratando dados str e colunas

In [135]:
df.columns

Index(['numero_fatura', 'codigo_produto', 'descricao', 'quantidade',
       'data_fatura', 'preco_unitario', 'id_cliente', 'pais'],
      dtype='str')

In [131]:
colunas_traduzidas = {
    "InvoiceNo": "numero_fatura",
    "StockCode": "codigo_produto",
    "Description": "descricao",
    "Quantity": "quantidade",
    "InvoiceDate": "data_fatura",
    "UnitPrice": "preco_unitario",
    "CustomerID": "id_cliente",
    "Country": "pais"
}


df = df.rename(columns=colunas_traduzidas)
df

,numero_fatura,codigo_produto,descricao,quantidade,data_fatura,preco_unitario,id_cliente,pais
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France

In [ ]:
print(df['pais'].unique())

df['pais'] = (df['pais'].str.strip())

<StringArray>
[      'United Kingdom',               'France',            'Australia',
          'Netherlands',              'Germany',               'Norway',
                 'EIRE',          'Switzerland',                'Spain',
               'Poland',             'Portugal',                'Italy',
              'Belgium',            'Lithuania',                'Japan',
              'Iceland',      'Channel Islands',              'Denmark',
               'Cyprus',               'Sweden',              'Austria',
               'Israel',              'Finland',              'Bahrain',
               'Greece',            'Hong Kong',            'Singapore',
              'Lebanon', 'United Arab Emirates',         'Saudi Arabia',
       'Czech Republic',               'Canada',          'Unspecified',
               'Brazil',                  'USA',   'European Community',
                'Malta',                  'RSA']
Length: 38, dtype: str

In [ ]:


'''
df.isnull().sum() #FAZER TRATAMENTO DOS NULLS

df = df.drop_duplicates(subset=["CustomerID"])

print(f"Quantidade de linhas: {df.shape[0]}\nQuantidade de Colunas: {df.shape[1]} ") 

df = df.drop_duplicates().reset_index(drop=True)
df
'''

KeyError: Index(['CustomerID'], dtype='str')